In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2.0,h,NaN,SS,Jellis,03-09-2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2.0,h,1480000.0,S,Biggin,03-12-2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2.0,h,1035000.0,S,Biggin,04-02-2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3.0,u,NaN,VB,Rounds,04-02-2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3.0,h,1465000.0,SP,Biggin,04-03-2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0

#### 1. Determine the no. of rows and no. of columns in the dataset

In [3]:
df.shape

(23678, 21)

rows: 23678 
columns: 21

#### 2. Display the datatypes of each column

In [5]:
df.dtypes

Suburb            object
Address           object
Rooms            float64
Type              object
Price            float64
Method            object
SellerG           object
Date              object
Distance         float64
Postcode         float64
Bedroom2         float64
Bathroom         float64
Car              float64
Landsize         float64
BuildingArea     float64
YearBuilt        float64
CouncilArea       object
Lattitude        float64
Longtitude       float64
Regionname        object
Propertycount    float64
dtype: object

#### 3. Determine the row indexes of rows having all null values (i.e. empty rows)

In [12]:
df.isnull().sum()

Suburb             131
Address            131
Rooms              131
Type               131
Price             5282
Method             131
SellerG            131
Date               131
Distance           132
Postcode           132
Bedroom2          4612
Bathroom          4615
Car               4757
Landsize          6268
BuildingArea     13660
YearBuilt        12138
CouncilArea       8022
Lattitude         4435
Longtitude        4435
Regionname         132
Propertycount      132
dtype: int64

In [13]:
# Total number of rows having null values in all columns
df.isnull().all(axis=1).sum()

131

In [15]:
# Rows indexes having null values in all columns
df.isnull().all(axis=1).index.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 ...]

#### 4. Determine the total number of empty rows and their percentage in whole dataset and remove them

In [19]:
total_length = len(df.index)
empty_rows = df.isnull().all(axis=1).sum()
total_length, empty_rows

(23678, 131)

In [21]:
percent = (empty_rows/total_length) * 100
print(round(percent, 2))

0.55

In [23]:
 df.dropna(how="all", inplace=True)

In [24]:
df.isnull().all(axis=1).sum()

0

In [25]:
len(df.index)

23547

#### 5. Determine the column names having missing values

In [26]:
df.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             5151
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          4481
Bathroom          4484
Car               4626
Landsize          6137
BuildingArea     13529
YearBuilt        12007
CouncilArea       7891
Lattitude         4304
Longtitude        4304
Regionname           1
Propertycount        1
dtype: int64

#### 6. Determine the missing values and their percentage in each column

In [30]:
print(round(df.isnull().sum()/len(df)*100,2))

Suburb            0.00
Address           0.00
Rooms             0.00
Type              0.00
Price            21.88
Method            0.00
SellerG           0.00
Date              0.00
Distance          0.00
Postcode          0.00
Bedroom2         19.03
Bathroom         19.04
Car              19.65
Landsize         26.06
BuildingArea     57.46
YearBuilt        50.99
CouncilArea      33.51
Lattitude        18.28
Longtitude       18.28
Regionname        0.00
Propertycount     0.00
dtype: float64

#### 7. Determine the row indexes having missing values

In [34]:
df.isnull().any(axis=1).index.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 ...]

#### 8. Determine the missing values and their percentage in each row.

In [45]:
print(round(df.isna().sum()/len(df)*100,2))

Suburb            0.00
Address           0.00
Rooms             0.00
Type              0.00
Price            21.88
Method            0.00
SellerG           0.00
Date              0.00
Distance          0.00
Postcode          0.00
Bedroom2         19.03
Bathroom         19.04
Car              19.65
Landsize         26.06
BuildingArea     57.46
YearBuilt        50.99
CouncilArea      33.51
Lattitude        18.28
Longtitude       18.28
Regionname        0.00
Propertycount     0.00
dtype: float64

#### 9. Determine the column names having more than 30% missing values and remove them from the dataset

In [47]:
cols = df.columns[round(df.isna().sum()/len(df)*100,2) > 30]
cols

Index(['BuildingArea', 'YearBuilt', 'CouncilArea'], dtype='object')

In [48]:
df.drop(cols, axis=1, inplace=True)
df.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'Lattitude', 'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

#### 10. Determine the number and percentage of rows having more than 5 missing values. If the percentage of such
#### rows is less than 20% then remove all these rows.

In [52]:
df[df.isnull().sum(axis=1)>5].shape

(4278, 18)

#### 11. Display the description of data and percentage of missing values still left column wise

In [55]:
df.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Propertycount
count,4278.000000,3.310000e+03,4277.000000,4277.000000,0.0,0.0,0.0,0.0,0.0,0.0,4277.000000
mean,2.989247,1.011133e+06,10.766729,3108.733692,NaN,NaN,NaN,NaN,NaN,NaN,7640.163666
std,0.954115,6.535334e+05,5.766499,98.014157,NaN,NaN,NaN,NaN,NaN,NaN,4820.197393
min,1.000000,1.210000e+05,0.000000,3000.000000,NaN,NaN,NaN,NaN,NaN,NaN,389.000000
25%,2.000000,6.050000e+05,7.400000,3046.000000,NaN,NaN,NaN,NaN,NaN,NaN,4168.000000
50%,3.000000,8.135000e+05,10.700000,3101.000000,NaN,NaN,NaN,NaN,NaN,NaN,6763.000000
75%,4.000000,1.220000e+06,13.300000,3148.000000,NaN,NaN,NaN,NaN,NaN,NaN,10331.000000
max,12.000000,6.460000e+06,47.300000,3978.000000,NaN,NaN,NaN,NaN,NaN,NaN,21650.000000

In [59]:
missing = (df.isnull().sum() * 100)/len(df)
print (round(missing, 2))

Suburb             0.00
Address            0.00
Rooms              0.00
Type               0.00
Price             22.63
Method             0.00
SellerG            0.00
Date               0.00
Distance           0.02
Postcode           0.02
Bedroom2         100.00
Bathroom         100.00
Car              100.00
Landsize         100.00
Lattitude        100.00
Longtitude       100.00
Regionname         0.02
Propertycount      0.02
dtype: float64

#### 12. Considering the 'Price' column as target variable which is to be predicted, how will you treat the missing values?
#### Give a brief explanation and treat the missing values in 'Price' column.

In [60]:
df['Price'].isnull().sum()

968

In [62]:
len(df)

4278

In [65]:
df = df[df['Price'].notnull()]
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,Lattitude,Longtitude,Regionname,Propertycount
15,Abbotsford,217 Langridge St,3.0,h,1000000.0,S,Jellis,08-10-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
16,Abbotsford,18a Mollison St,2.0,t,745000.0,S,Jellis,08-10-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
19,Abbotsford,403/609 Victoria St,2.0,u,542000.0,S,Dingle,08-10-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
21,Abbotsford,25/84 Trenerry Cr,2.0,u,760000.0,SP,Biggin,10-12-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
22,Abbotsford,106/119 Turner St,1.0,u,481000.0,SP,Purplebricks,10-12-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
27,Abbotsford,13/84 Trenerry Cr,1.0,u,500000.0,S,Biggin,12-11-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
34,Abbotsford,250 Langridge St,2.0,t,847000.0,S,Jellis,16-07-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
46,Abbotsford,65/80 Trenerry Cr,1.0,u,480000.0,S,Biggin,19-11-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
47,Abbotsford,119/52 Nicholson St,1.0,u,423500.0,S,hockingstuart,22-05-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
53,Abbotsford,49/84 Trenerry Cr,2.0,h,700000.0,S,Biggin,23-04-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
63,Abbotsford,82/84 Trenerry Cr,2.0,u,970000.0,SP,Biggin,28-05-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
66,Abbotsford,40/80 Trenerry Cr,3.0,h,927000.0,S,Biggin,30-07-2016,2.5,3067.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4019.0
75,Airport West,4/9 West Ct,2.0,t,420000.0,VB,Barry,04-06-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
76,Airport West,1/36 York St,3.0,t,500000.0,VB,Nelson,04-06-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
77,Airport West,33 Bowes Av,5.0,h,1035000.0,S,Airport,06-08-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
78,Airport West,89 Bowes Av,4.0,h,960000.0,S,Barry,06-08-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
79,Airport West,45 Laurence Av,4.0,h,960000.0,S,Nelson,06-08-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
85,Airport West,81a Roberts Rd,3.0,h,680000.0,VB,Nelson,08-10-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
88,Airport West,3/24 Elstone Av,3.0,u,600000.0,VB,Nelson,10-09-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
90,Airport West,37a North St,3.0,t,760000.0,PI,Barry,10-12-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
92,Airport West,1/69 Bowes Av,3.0,u,580000.0,VB,Nelson,12-11-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
93,Airport West,2/9 El Reno Cr,3.0,h,725000.0,PI,Ray,12-11-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
94,Airport West,92 McNamara Av,4.0,h,758000.0,S,Jellis,13-08-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
96,Airport West,20 Creswell Av,3.0,h,970000.0,S,Barry,14-05-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
98,Airport West,71 Bowes Av,4.0,h,985000.0,S,Barry,15-10-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
100,Airport West,2/112 Parer Rd,2.0,u,509500.0,SP,Nelson,15-10-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
108,Airport West,7 McNamara Av,3.0,h,715000.0,S,Barry,17-09-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
112,Airport West,1/41 Hillside Gr,2.0,t,460000.0,VB,Nelson,18-06-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
116,Airport West,7/42 York St,3.0,u,445000.0,S,Brad,22-05-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
124,Airport West,4/40 McNamara Av,2.0,u,474000.0,PI,Barry,26-07-2016,13.5,3042.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3464.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23352,Ivanhoe,2/7 Ambrose St,4.0,t,1175000.0,S,McGrath,26-08-2017,7.8,3079.0,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Metropolitan,5549.0
23384,Kingsbury,15A Curtain St,4.0,h,900000.0,S,Barry,26-08-2017,12.1,3083.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,1414.0
23385,Knoxfield,2/49 Allister Cl,4.0,h,795000.0,SP,Barry,26-08-2017,23.3,3180.0,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Metropolitan,2949.0
23395,Lilydale,30 Lakeview Dr,4.0,h,840000.0,S,Fletchers,26-08-2017,29.9,3140.0,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Victoria,6732.0
23398,MacLeod,2/56 Braid Hill Rd,3.0,t,961500.0,S,Ray,26-08-2017,12.7,3085.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4168.0
23399,MacLeod,32 Chapman St,3.0,h,998000.0,S,Purplebricks,26-08-2017,12.7,3085.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4168.0
23401,MacLeod,4 Tucker Wy,4.0,h,831000.0,S,Ray,26-08-2017,12.7,3085.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4168.0
23402,Maidstone,88a Ballarat Rd,3.0,t,706000.0,S,Sweeney,26-08-2017,6.4,3012.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,3873.0
23421,Meadow Heights,22 Lightwood Cr,5.0,h,710000.0,S,YPA,26-08-2017,17.4,3048.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,4704.0
23431,Mentone,20A Winsome St,3.0,t,905000.0,S,Hodges,26-08-2017,20.0,3194.0,NaN,NaN,NaN,NaN,NaN,NaN,South-Eastern Metropolitan,6162.0
23433,Mickleham,3 Selkirk Wy,2.0,h,335000.0,S,YPA,26-08-2017,20.6,3064.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,1158.0
23449,Moonee Ponds,55 Pattison St,2.0,h,700000.0,VB,Nelson,26-08-2017,6.2,3039.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,6232.0
23468,Mulgrave,45 Carson St,3.0,t,826000.0,S,Win,26-08-2017,18.8,3170.0,NaN,NaN,NaN,NaN,NaN,NaN,South-Eastern Metropolitan,7113.0
23483,Northcote,2/241 Heidelberg Rd,2.0,t,770000.0,VB,Nelson,26-08-2017,5.3,3070.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,11364.0
23515,Prahran,82 Murray St,2.0,h,1500000.0,VB,RT,26-08-2017,4.6,3181.0,NaN,NaN,NaN,NaN,NaN,NaN,Southern Metropolitan,7717.0
23528,Reservoir,5a Kyneton Av,3.0,u,635000.0,S,Barry,26-08-2017,12.0,3073.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,21650.0
23540,Richmond,10/9 Westbank Tce,2.0,u,410000.0,PI,Jellis,26-08-2017,2.4,3121.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,14949.0
23543,Ringwood East,2/16 Bronhill Rd,4.0,t,850000.0,VB,McGrath,26-08-2017,21.3,3135.0,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Metropolitan,4407.0
23549,Rowville,8 Lakeside Bvd,3.0,h,905000.0,S,Biggin,26-08-2017,23.5,3178.0,NaN,NaN,NaN,NaN,NaN,NaN,South-Eastern Metropolitan,11667.0
23568,South Morang,2/5 Briar Ct,2.0,u,310000.0,S,HAR,26-08-2017,20.5,3752.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,7969.0
23573,South Morang,18 Warbler Wk,3.0,h,691000.0,S,Millership,26-08-2017,20.5,3752.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,7969.0
23577,South Yarra,20/22 Mona Pl,2.0,u,500000.0,VB,Greg,26-08-2017,2.7,3141.0,NaN,NaN,NaN,NaN,NaN,NaN,Southern Metropolitan,14887.0
23580,St Albans,1/52 Conrad St,2.0,t,457500.0,S,Barry,26-08-2017,14.0,3021.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,14042.0
23584,St Albans,39b Power St,2.0,u,515000.0,PI,Brad,26-08-2017,14.0,3021.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,14042.0
23603,Sunshine West,65 Europa Bnd,1.0,h,460000.0,S,S&L,26-08-2017,10.5,3020.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,6763.0
23626,Templestowe Lower,1/207 Manningham Rd,2.0,u,550000.0,PI,Barry,26-08-2017,12.4,3107.0,NaN,NaN,NaN,NaN,NaN,NaN,Eastern Metropolitan,5420.0
23630,Thornbury,1/128 Dundas St,2.0,t,770000.0,PI,McGrath,26-08-2017,7.0,3071.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,8870.0
23633,Thornbury,111 Pender St,2.0,t,858000.0,S,Jellis,26-08-2017,7.0,3071.0,NaN,NaN,NaN,NaN,NaN,NaN,Northern Metropolitan,8870.0
23639,Toorak,21/1059 Malvern Rd,2.0,u,720000.0,VB,Beller,26-08-2017,4.1,3142.0,NaN,NaN,NaN,NaN,NaN,NaN,Southern Metropolitan,7217.0
23662,Werribee,91 Latham St,4.0,h,540000.0,PI,Triwest,26-08-2017,14.7,3030.0,NaN,NaN,NaN,NaN,NaN,NaN,Western Metropolitan,16166.0

#### 13. Now check the percentage of missing values in each column again, if missing values exist, treat it with the most
#### suitable method.

In [67]:
missing = (df.isnull().sum() * 100)/len(df)
print (round(missing, 2))

Suburb             0.00
Address            0.00
Rooms              0.00
Type               0.00
Price              0.00
Method             0.00
SellerG            0.00
Date               0.00
Distance           0.03
Postcode           0.03
Bedroom2         100.00
Bathroom         100.00
Car              100.00
Landsize         100.00
Lattitude        100.00
Longtitude       100.00
Regionname         0.03
Propertycount      0.03
dtype: float64

In [68]:
# We can see that Bedroom2, Bathroom, Car, Landsize, Lattitude, Longtitude have 100% null data so can be dropped.
df=df.drop(['Bedroom2', 'Bathroom','Car', 'Landsize','Lattitude', 'Longtitude'], axis = 1)
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Regionname,Propertycount
15,Abbotsford,217 Langridge St,3.0,h,1000000.0,S,Jellis,08-10-2016,2.5,3067.0,Northern Metropolitan,4019.0
16,Abbotsford,18a Mollison St,2.0,t,745000.0,S,Jellis,08-10-2016,2.5,3067.0,Northern Metropolitan,4019.0
19,Abbotsford,403/609 Victoria St,2.0,u,542000.0,S,Dingle,08-10-2016,2.5,3067.0,Northern Metropolitan,4019.0
21,Abbotsford,25/84 Trenerry Cr,2.0,u,760000.0,SP,Biggin,10-12-2016,2.5,3067.0,Northern Metropolitan,4019.0
22,Abbotsford,106/119 Turner St,1.0,u,481000.0,SP,Purplebricks,10-12-2016,2.5,3067.0,Northern Metropolitan,4019.0
27,Abbotsford,13/84 Trenerry Cr,1.0,u,500000.0,S,Biggin,12-11-2016,2.5,3067.0,Northern Metropolitan,4019.0
34,Abbotsford,250 Langridge St,2.0,t,847000.0,S,Jellis,16-07-2016,2.5,3067.0,Northern Metropolitan,4019.0
46,Abbotsford,65/80 Trenerry Cr,1.0,u,480000.0,S,Biggin,19-11-2016,2.5,3067.0,Northern Metropolitan,4019.0
47,Abbotsford,119/52 Nicholson St,1.0,u,423500.0,S,hockingstuart,22-05-2016,2.5,3067.0,Northern Metropolitan,4019.0
53,Abbotsford,49/84 Trenerry Cr,2.0,h,700000.0,S,Biggin,23-04-2016,2.5,3067.0,Northern Metropolitan,4019.0
63,Abbotsford,82/84 Trenerry Cr,2.0,u,970000.0,SP,Biggin,28-05-2016,2.5,3067.0,Northern Metropolitan,4019.0
66,Abbotsford,40/80 Trenerry Cr,3.0,h,927000.0,S,Biggin,30-07-2016,2.5,3067.0,Northern Metropolitan,4019.0
75,Airport West,4/9 West Ct,2.0,t,420000.0,VB,Barry,04-06-2016,13.5,3042.0,Western Metropolitan,3464.0
76,Airport West,1/36 York St,3.0,t,500000.0,VB,Nelson,04-06-2016,13.5,3042.0,Western Metropolitan,3464.0
77,Airport West,33 Bowes Av,5.0,h,1035000.0,S,Airport,06-08-2016,13.5,3042.0,Western Metropolitan,3464.0
78,Airport West,89 Bowes Av,4.0,h,960000.0,S,Barry,06-08-2016,13.5,3042.0,Western Metropolitan,3464.0
79,Airport West,45 Laurence Av,4.0,h,960000.0,S,Nelson,06-08-2016,13.5,3042.0,Western Metropolitan,3464.0
85,Airport West,81a Roberts Rd,3.0,h,680000.0,VB,Nelson,08-10-2016,13.5,3042.0,Western Metropolitan,3464.0
88,Airport West,3/24 Elstone Av,3.0,u,600000.0,VB,Nelson,10-09-2016,13.5,3042.0,Western Metropolitan,3464.0
90,Airport West,37a North St,3.0,t,760000.0,PI,Barry,10-12-2016,13.5,3042.0,Western Metropolitan,3464.0
92,Airport West,1/69 Bowes Av,3.0,u,580000.0,VB,Nelson,12-11-2016,13.5,3042.0,Western Metropolitan,3464.0
93,Airport West,2/9 El Reno Cr,3.0,h,725000.0,PI,Ray,12-11-2016,13.5,3042.0,Western Metropolitan,3464.0
94,Airport West,92 McNamara Av,4.0,h,758000.0,S,Jellis,13-08-2016,13.5,3042.0,Western Metropolitan,3464.0
96,Airport West,20 Creswell Av,3.0,h,970000.0,S,Barry,14-05-2016,13.5,3042.0,Western Metropolitan,3464.0
98,Airport West,71 Bowes Av,4.0,h,985000.0,S,Barry,15-10-2016,13.5,3042.0,Western Metropolitan,3464.0
100,Airport West,2/112 Parer Rd,2.0,u,509500.0,SP,Nelson,15-10-2016,13.5,3042.0,Western Metropolitan,3464.0
108,Airport West,7 McNamara Av,3.0,h,715000.0,S,Barry,17-09-2016,13.5,3042.0,Western Metropolitan,3464.0
112,Airport West,1/41 Hillside Gr,2.0,t,460000.0,VB,Nelson,18-06-2016,13.5,3042.0,Western Metropolitan,3464.0
116,Airport West,7/42 York St,3.0,u,445000.0,S,Brad,22-05-2016,13.5,3042.0,Western Metropolitan,3464.0
124,Airport West,4/40 McNamara Av,2.0,u,474000.0,PI,Barry,26-07-2016,13.5,3042.0,Western Metropolitan,3464.0
...,...,...,...,...,...,...,...,...,...,...,...,...
23352,Ivanhoe,2/7 Ambrose St,4.0,t,1175000.0,S,McGrath,26-08-2017,7.8,3079.0,Eastern Metropolitan,5549.0
23384,Kingsbury,15A Curtain St,4.0,h,900000.0,S,Barry,26-08-2017,12.1,3083.0,Northern Metropolitan,1414.0
23385,Knoxfield,2/49 Allister Cl,4.0,h,795000.0,SP,Barry,26-08-2017,23.3,3180.0,Eastern Metropolitan,2949.0
23395,Lilydale,30 Lakeview Dr,4.0,h,840000.0,S,Fletchers,26-08-2017,29.9,3140.0,Eastern Victoria,6732.0
23398,MacLeod,2/56 Braid Hill Rd,3.0,t,961500.0,S,Ray,26-08-2017,12.7,3085.0,Northern Metropolitan,4168.0
23399,MacLeod,32 Chapman St,3.0,h,998000.0,S,Purplebricks,26-08-2017,12.7,3085.0,Northern Metropolitan,4168.0
23401,MacLeod,4 Tucker Wy,4.0,h,831000.0,S,Ray,26-08-2017,12.7,3085.0,Northern Metropolitan,4168.0
23402,Maidstone,88a Ballarat Rd,3.0,t,706000.0,S,Sweeney,26-08-2017,6.4,3012.0,Western Metropolitan,3873.0
23421,Meadow Heights,22 Lightwood Cr,5.0,h,710000.0,S,YPA,26-08-2017,17.4,3048.0,Northern Metropolitan,4704.0
23431,Mentone,20A Winsome St,3.0,t,905000.0,S,Hodges,26-08-2017,20.0,3194.0,South-Eastern Metropolitan,6162.0
23433,Mickleham,3 Selkirk Wy,2.0,h,335000.0,S,YPA,26-08-2017,20.6,3064.0,Northern Metropolitan,1158.0
23449,Moonee Ponds,55 Pattison St,2.0,h,700000.0,VB,Nelson,26-08-2017,6.2,3039.0,Western Metropolitan,6232.0
23468,Mulgrave,45 Carson St,3.0,t,826000.0,S,Win,26-08-2017,18.8,3170.0,South-Eastern Metropolitan,7113.0
23483,Northcote,2/241 Heidelberg Rd,2.0,t,770000.0,VB,Nelson,26-08-2017,5.3,3070.0,Northern Metropolitan,11364.0
23515,Prahran,82 Murray St,2.0,h,1500000.0,VB,RT,26-08-2017,4.6,3181.0,Southern Metropolitan,7717.0
23528,Reservoir,5a Kyneton Av,3.0,u,635000.0,S,Barry,26-08-2017,12.0,3073.0,Northern Metropolitan,21650.0
23540,Richmond,10/9 Westbank Tce,2.0,u,410000.0,PI,Jellis,26-08-2017,2.4,3121.0,Northern Metropolitan,14949.0
23543,Ringwood East,2/16 Bronhill Rd,4.0,t,850000.0,VB,McGrath,26-08-2017,21.3,3135.0,Eastern Metropolitan,4407.0
23549,Rowville,8 Lakeside Bvd,3.0,h,905000.0,S,Biggin,26-08-2017,23.5,3178.0,South-Eastern Metropolitan,11667.0
23568,South Morang,2/5 Briar Ct,2.0,u,310000.0,S,HAR,26-08-2017,20.5,3752.0,Northern Metropolitan,7969.0
23573,South Morang,18 Warbler Wk,3.0,h,691000.0,S,Millership,26-08-2017,20.5,3752.0,Northern Metropolitan,7969.0
23577,South Yarra,20/22 Mona Pl,2.0,u,500000.0,VB,Greg,26-08-2017,2.7,3141.0,Southern Metropolitan,14887.0
23580,St Albans,1/52 Conrad St,2.0,t,457500.0,S,Barry,26-08-2017,14.0,3021.0,Western Metropolitan,14042.0
23584,St Albans,39b Power St,2.0,u,515000.0,PI,Brad,26-08-2017,14.0,3021.0,Western Metropolitan,14042.0
23603,Sunshine West,65 Europa Bnd,1.0,h,460000.0,S,S&L,26-08-2017,10.5,3020.0,Western Metropolitan,6763.0
23626,Templestowe Lower,1/207 Manningham Rd,2.0,u,550000.0,PI,Barry,26-08-2017,12.4,3107.0,Eastern Metropolitan,5420.0
23630,Thornbury,1/128 Dundas St,2.0,t,770000.0,PI,McGrath,26-08-2017,7.0,3071.0,Northern Metropolitan,8870.0
23633,Thornbury,111 Pender St,2.0,t,858000.0,S,Jellis,26-08-2017,7.0,3071.0,Northern Metropolitan,8870.0
23639,Toorak,21/1059 Malvern Rd,2.0,u,720000.0,VB,Beller,26-08-2017,4.1,3142.0,Southern Metropolitan,7217.0
23662,Werribee,91 Latham St,4.0,h,540000.0,PI,Triwest,26-08-2017,14.7,3030.0,Western Metropolitan,16166.0

In [69]:
df['Distance'].fillna(df['Distance'].mean(), inplace=True)
df['Postcode'].fillna(df['Postcode'].mode(), inplace=True)
df['Regionname'].fillna(df['Regionname'].mode(), inplace=True)
df['Propertycount'].fillna(df['Propertycount'].mean(), inplace=True)

#### 14. Now since you have completed your data cleaning, determine the number and percentage of columns removed

In [72]:
df.shape

(3310, 12)

In [73]:
print (round((12/21) * 100, 2))

57.14

#### 15. Determine the number and percentage of rows removed in whole process. Also comment briefly that according
#### to you the amount of data lost is justified or not

In [74]:
# Data shape post cleaning
df.shape

(3310, 12)

In [75]:
print (round((3310/23678) * 100, 2))

13.98